move_group:
  controller_list:
    - name: ""
      action_ns: joint_trajectory_action
      type: FollowJointTrajectory
      joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

jog_joint_node:
  controller_name: arm_controller
  joint_names: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

jog_frame_node:
  group_names:
    - manipulator
  link_names:
    - tool0
